function y = filterr(x)
%FILTERR Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 12-Nov-2014 17:07:25

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 60;     % First Stopband Frequency
    % Fpass1 = 70;     % First Passband Frequency
    % Fpass2 = 80;     % Second Passband Frequency
    % Fstop2 = 90;     % Second Stopband Frequency
    % Astop1 = 60;     % First Stopband Attenuation (dB)
    % Apass  = 1;      % Passband Ripple (dB)
    % Astop2 = 80;     % Second Stopband Attenuation (dB)
    % Fs     = 10000;  % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'ellip', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.9967465894589 1 1 -1.99691765298486 ...
        0.999440190010085; 1 -1.99849836923787 1 1 -1.99757371334708 ...
        0.999509549090625; 1 -1.99594034959766 1 1 -1.99607043919792 ...
        0.998472626360116; 1 -1.99879674360038 1 1 -1.99656457897689 ...
        0.998595499561364; 1 0 -1 1 -1.99590533916693 0.998113645763962], ...
        'ScaleValues', [0.187307881677876; 0.187307881677876; ...
        0.14500996819628; 0.14500996819628; 0.00313863990100359; 1]);
end

y = step(Hd,x);


